# .github/workflows/release-github.yml
name: Release on GitHub

on:
  workflow_call:
    inputs:
      release_title:
        description: 'Release title'
        required: true
        type: string
      release_body:
        description: 'Release description'
        required: true
        type: string
    secrets:
      PAT_TOKEN:
        description: 'GitHub Personal Access Token'
        required: true

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    outputs:
      wheels_zip: ${{ steps.zip.outputs.wheels_zip }}
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: Zip wheels
        id: zip
        run: |
          mkdir -p dist
          find dist -type f -name '*.whl' | zip -j dist/wheels.zip -@
          echo "wheels_zip=dist/wheels.zip" >> $GITHUB_OUTPUT

  create-release:
    needs: prepare-release
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        id: create_release
        shell: bash
        run: |
          set -euo pipefail

          TAG="${{ github.ref_name }}"
          echo "Creating release for tag '$TAG'…"

          http_resp=$(curl --silent --output resp.json --write-out "%{http_code}" \
            -X POST https://api.github.com/repos/${{ github.repository }}/releases \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            --data @- <<EOF
          {
            "tag_name":   "$TAG",
            "name":       "${{ inputs.release_title }}",
            "body":       "${{ inputs.release_body }}",
            "prerelease": true
          }
          EOF
          )

          echo "HTTP status: $http_resp"
          cat resp.json

          if [[ "$http_resp" -ne 201 ]]; then
            echo "::error::Failed to create release (status $http_resp)"
            exit 1
          fi

          upload_url=$(jq -r .upload_url resp.json)
          upload_url=${upload_url%%\{*}
          echo "upload_url=$upload_url" >> $GITHUB_OUTPUT

      - name: Upload Release Assets
        if: steps.create_release.outputs.upload_url != ''
        run: |
          for file in "${{ needs.prepare-release.outputs.wheels_zip }}"; do
            echo "Uploading asset: $file"
            curl --silent --data-binary @"$file" \
              -H "Content-Type: application/octet-stream" \
              -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
              "${{ steps.create_release.outputs.upload_url }}?name=$(basename "$file")"
          done
